version: '3.7'

services:
    client:
        stdin_open: true
        build:
            context: ./client
            dockerfile: Dockerfile
        ports:
            - 3000:3000
        volumes:
            - "/app/node_modules"
            - "./client:/app"
        environment:
            - CHOKIDAR_USEPOLLING=true
